# Site settings
title: Esther Leytush
email: eleytush@gmail.com

url: "https://estherleytush.com"
baseurl: ""

include: ['_static']

me:
  company: 'Brightside'
  company_url: "https://www.brightside.com/"

resume:
  download_url: esther_leytush_software_engineer_resume.pdf
