version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.2-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Install Firebase
          command: sudo npm install -g firebase-tools
      - run:
          name: Jekyll build
          command: bundle exec jekyll build --verbose
      - run:
          name: Firebase deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
